blank_issues_enabled: false
contact_links:
  - name: 📖 Contribution Guide
    url: https://github.com/peter-neumann-dev/responsive-image-linter/blob/main/CONTRIBUTING.md
    about: Please read through before making any contribution.
